DROP SCHEMA IF EXISTS Hardware_informatico;
CREATE SCHEMA IF NOT EXISTS Hardware_informatico;
USE Hardware_informatico;


DROP TABLE IF EXISTS Productos;
CREATE TABLE IF NOT EXISTS Productos (
ID_Producto SMALLINT AUTO_INCREMENT,
Marca VARCHAR(20) NOT NULL,
Modelo VARCHAR(80) NOT NULL,
Tipo CHAR(12) NOT NULL,
Stock TINYINT NOT NULL,
Costo DECIMAL(10, 2) NOT NULL,
Precio DECIMAL(10, 2) NOT NULL,
PRIMARY KEY (ID_Producto)
);

DROP TABLE IF EXISTS Motherboard;
CREATE TABLE IF NOT EXISTS Motherboard (
ID_Motherboard SMALLINT AUTO_INCREMENT,
Zocalo CHAR(10) NOT NULL,
Chipset VARCHAR(20) NOT NULL,
Slots_RAM TINYINT NOT NULL,
Tecnologia_RAM CHAR(4) NOT NULL,
Vel_Max_RAM CHAR(10) NOT NULL,
Puertos_PCI TINYINT NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_Motherboard),
CONSTRAINT `FK_Motherboard_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS Procesador;
CREATE TABLE IF NOT EXISTS Procesador (
ID_Procesador SMALLINT AUTO_INCREMENT,
Zocalo CHAR(10) NOT NULL,
Chipset CHAR(10) NOT NULL,
Cant_Nucleos TINYINT NOT NULL,
Vel_Max CHAR(10) NOT NULL,
VGA VARCHAR(20) NOT NULL,
Cooler ENUM('Si', 'No') NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_Procesador),
CONSTRAINT `FK_Procesador_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS RAM;
CREATE TABLE IF NOT EXISTS RAM (
ID_RAM SMALLINT AUTO_INCREMENT,
Tecnologia CHAR(4) NOT NULL,
Vel_Max CHAR(10) NOT NULL,
Capacidad CHAR(10) NOT NULL,
PC_Notebook ENUM('PC', 'Notebook') NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_RAM),
CONSTRAINT `FK_RAM_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS SSD;
CREATE TABLE IF NOT EXISTS SSD (
ID_SSD SMALLINT AUTO_INCREMENT,
Tecnologia CHAR(10) NOT NULL,
Capacidad CHAR(10) NOT NULL,
Vel_Lectura CHAR(10) NOT NULL,
Vel_Escritura CHAR(10) NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_SSD),
CONSTRAINT `FK_SSD_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS HDD;
CREATE TABLE IF NOT EXISTS HDD (
ID_HDD SMALLINT AUTO_INCREMENT,
Capacidad CHAR(10) NOT NULL,
Vel_Lectura CHAR(10) NOT NULL,
Vel_Escritura CHAR(10) NOT NULL,
Vel_Rotacion CHAR(10) NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_HDD),
CONSTRAINT `FK_HDD_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS VGA;
CREATE TABLE IF NOT EXISTS VGA (
ID_VGA SMALLINT AUTO_INCREMENT,
Capacidad CHAR(10) NOT NULL,
Tasa_Reloj CHAR(10) NOT NULL,
Consumo CHAR(10) NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_VGA),
CONSTRAINT `FK_VGA_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS Fuente;
CREATE TABLE IF NOT EXISTS Fuente (
ID_Fuente SMALLINT AUTO_INCREMENT,
Potencia CHAR(10) NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_Fuente),
CONSTRAINT `FK_Fuente_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS Gabinete;
CREATE TABLE IF NOT EXISTS Gabinete (
ID_Gabinete SMALLINT AUTO_INCREMENT,
Formato CHAR(10) NOT NULL,
Color CHAR(10) NOT NULL,
Fuente CHAR(10) NOT NULL,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_Gabinete),
CONSTRAINT `FK_Gabinete_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS PC;
CREATE TABLE IF NOT EXISTS PC (
ID_PC SMALLINT AUTO_INCREMENT,
ID_Producto SMALLINT NOT NULL,
PRIMARY KEY (ID_PC),
CONSTRAINT `FK_PC(ID_Producto)_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS PC_Componentes;
CREATE TABLE IF NOT EXISTS PC_Componentes (
ID_PC_Comp SMALLINT AUTO_INCREMENT,
ID_PC SMALLINT NOT NULL,
ID_Producto SMALLINT NOT NULL,
Cantidad SMALLINT NOT NULL,
PRIMARY KEY (ID_PC_Comp),
CONSTRAINT `FK_PC_Componentes(ID_PC)_PC` FOREIGN KEY (ID_PC) REFERENCES PC(ID_PC),
CONSTRAINT `FK_PC_Componentes(ID_Producto)_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto)
);

DROP TABLE IF EXISTS Clientes;
CREATE TABLE IF NOT EXISTS Clientes (
ID_Cliente SMALLINT AUTO_INCREMENT,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL,
Direccion VARCHAR(100) NOT NULL,
Localidad VARCHAR(30) NOT NULL,
Provincia CHAR(19) NOT NULL,
CP CHAR(8),
Telefono CHAR(15),
PRIMARY KEY (ID_Cliente)
);

DROP TABLE IF EXISTS Vendedores;
CREATE TABLE IF NOT EXISTS Vendedores (
ID_Vendedor SMALLINT AUTO_INCREMENT,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_Vendedor)
);

DROP TABLE IF EXISTS Ventas;
CREATE TABLE IF NOT EXISTS Ventas (
ID_Venta SMALLINT AUTO_INCREMENT,
Nro_Venta SMALLINT NOT NULL,
ID_Producto SMALLINT NOT NULL,
Cantidad SMALLINT NOT NULL,
Precio DECIMAL(12, 2) NOT NULL,
Descuento TINYINT,
Fecha DATETIME NOT NULL,
Cliente SMALLINT NOT NULL,
Vendedor SMALLINT NOT NULL,
PRIMARY KEY (ID_Venta),
CONSTRAINT `FK_Ventas_Productos` FOREIGN KEY (ID_Producto) REFERENCES Productos(ID_Producto),
CONSTRAINT `FK_Ventas_Clientes` FOREIGN KEY (Cliente) REFERENCES Clientes(ID_Cliente),
CONSTRAINT `FK_Ventas_Vendedores` FOREIGN KEY (Vendedor) REFERENCES Vendedores(ID_Vendedor)
);

DROP TABLE IF EXISTS LOG_Productos;
CREATE TABLE IF NOT EXISTS LOG_Productos (
	ID_Log INT AUTO_INCREMENT,
    ID_Producto VARCHAR(255),
	Accion CHAR(6),
	Marca VARCHAR(255),
	Modelo VARCHAR(255),
	Tipo VARCHAR(255),
    Stock VARCHAR(255),
    Costo VARCHAR(255),
	Precio VARCHAR(255),
	Usuario VARCHAR(50),
	Fecha DATETIME,
	PRIMARY KEY (ID_Log)
);

DROP TABLE IF EXISTS LOG_PC_Componentes;
CREATE TABLE IF NOT EXISTS LOG_PC_Componentes (
	ID_Log INT AUTO_INCREMENT,
    ID_PC_Comp VARCHAR(255),
	Accion CHAR(6),
	ID_PC VARCHAR(100),
	ID_Producto VARCHAR(100),
	Cantidad VARCHAR(100),
	Usuario VARCHAR(50),
	Fecha DATETIME,
	PRIMARY KEY (ID_Log)
);